# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORGANISATION', models.CharField(max_length=200)),
                ('PRODUCT', models.CharField(max_length=200)),
                ('DATE', models.CharField(max_length=20)),
                ('EVENT', models.CharField(max_length=200)),
                ('TIME', models.CharField(max_length=200)),
                ('LOCATION', models.CharField(max_length=200)),
                ('PERSON', models.CharField(max_length=200)),
                ('GPE', models.CharField(max_length=200)),
            ],
        ),
    ]
